
CREATE TABLE categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  is_native BOOLEAN DEFAULT 0,
  parent_id INTEGER,
  group_name TEXT,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_categories_type ON categories(type);
CREATE INDEX idx_categories_parent_id ON categories(parent_id);
CREATE INDEX idx_categories_group_name ON categories(group_name);

INSERT INTO categories (name, type, is_native, group_name, display_order) VALUES
('Descontos Concedidos', 'expense', 1, 'RECEITAS OPERACIONAIS', 1),
('Juros Recebidos', 'income', 1, 'RECEITAS OPERACIONAIS', 2),
('Multas Recebidas', 'income', 1, 'RECEITAS OPERACIONAIS', 3),
('Outras receitas', 'income', 1, 'RECEITAS OPERACIONAIS', 4),
('Compras de fornecedores', 'expense', 0, 'CUSTOS OPERACIONAIS', 1),
('Custo serviço prestado', 'expense', 0, 'CUSTOS OPERACIONAIS', 2),
('Custos produto vendido', 'expense', 0, 'CUSTOS OPERACIONAIS', 3),
('Impostos sobre receita', 'expense', 0, 'CUSTOS OPERACIONAIS', 4),
('INSS Retido sobre a Receita', 'expense', 1, 'CUSTOS OPERACIONAIS', 5),
('Outras Retenções sobre a Receita', 'expense', 1, 'CUSTOS OPERACIONAIS', 6),
('CSLL Retido sobre a Receita', 'expense', 1, 'CUSTOS OPERACIONAIS', 7),
('ISS Retido sobre a Receita', 'expense', 1, 'CUSTOS OPERACIONAIS', 8),
('PIS Retido sobre a Receita', 'expense', 1, 'CUSTOS OPERACIONAIS', 9),
('IRPJ Retido sobre a Receita', 'expense', 1, 'CUSTOS OPERACIONAIS', 10),
('COFINS Retido sobre a Receita', 'expense', 1, 'CUSTOS OPERACIONAIS', 11),
('Compras - Embalagens', 'expense', 0, 'CUSTOS OPERACIONAIS', 12),
('Frete sobre Compras', 'expense', 0, 'CUSTOS OPERACIONAIS', 13),
('Aluguel e condomínio', 'expense', 0, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 1),
('Descontos Recebidos', 'income', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 2),
('Juros Pagos', 'expense', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 3),
('Luz, água e outros', 'expense', 0, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 4),
('Material de escritório', 'expense', 0, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 5),
('Multas Pagas', 'expense', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 6),
('Outras despesas', 'expense', 0, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 7),
('Salários, encargos e benefícios', 'expense', 0, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 8),
('Serviços contratados', 'expense', 0, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 9),
('Taxas e contribuições', 'expense', 0, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 10),
('Pagamento de CSLL Retido', 'expense', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 11),
('Pagamento de Cofins Retido', 'expense', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 12),
('Pagamento de INSS Retido', 'expense', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 13),
('Pagamento de IRPJ Retido', 'expense', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 14),
('Pagamento de Outras retenções', 'expense', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 15),
('Pagamento de ISS Retido', 'expense', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 16),
('Pagamento de PIS Retido', 'expense', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 17),
('CSLL Retido sobre Pagamentos', 'income', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 18),
('INSS Retido sobre Pagamentos', 'income', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 19),
('IRPJ Retido sobre Pagamentos', 'income', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 20),
('COFINS Retido sobre Pagamentos', 'income', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 21),
('PIS Retido sobre Pagamentos', 'income', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 22),
('ISS Retido sobre Pagamentos', 'income', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 23),
('Outras Retenções sobre Pagamentos', 'income', 1, 'DESPESAS OPERACIONAIS E OUTRAS RECEITAS', 24),
('Compra de ativo fixo', 'expense', 0, 'ATIVIDADES DE INVESTIMENTO', 1),
('Venda de ativo fixo', 'income', 0, 'ATIVIDADES DE INVESTIMENTO', 2),
('Aporte de capital', 'income', 0, 'ATIVIDADES DE FINANCIAMENTO', 1),
('Obtenção de empréstimo', 'income', 0, 'ATIVIDADES DE FINANCIAMENTO', 2),
('Pagamento de empréstimo', 'expense', 0, 'ATIVIDADES DE FINANCIAMENTO', 3),
('Retirada de capital', 'expense', 0, 'ATIVIDADES DE FINANCIAMENTO', 4);
